version: '2.3'
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: tele_bot
      MYSQL_ROOT_PASSWORD: 3nYzRaLtpM4
  pma:
    image: nazarpc/phpmyadmin
    ports:
      - 8080:80
    environment:
      UPLOAD_SIZE: 1G
      MYSQL_HOST: db
volumes:
  mysql-data:
    driver: local